# Data Validation

Sanity checks on all three master datasets before analysis: correct shape, no missing values, correct state counts, and plausible price ranges.

In [1]:
import pandas as pd

petrol_master = pd.read_csv("../data/processed/petrol_master.csv")
diesel_master = pd.read_csv("../data/processed/diesel_master.csv")
cpi_food_master = pd.read_csv("../data/processed/cpi_food_master.csv")

## Petrol Checks

In [2]:
petrol_master.shape

(37, 32)

In [3]:
petrol_master.isna().sum()

State      0
2023-11    0
2023-12    0
2024-01    0
2024-02    0
2024-03    0
2024-04    0
2024-05    0
2024-06    0
2024-07    0
2024-08    0
2024-09    0
2024-10    0
2024-11    0
2024-12    0
2025-01    0
2025-02    0
2025-03    0
2025-04    0
2025-05    0
2025-06    0
2025-07    0
2025-08    0
2025-09    0
2025-10    0
2025-11    0
2025-12    0
2026-01    0
2026-02    0
2026-03    0
2026-04    0
2026-05    0
dtype: int64

In [4]:
petrol_master["State"].nunique()

37

In [5]:
petrol_master.describe()

,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,...,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,648.933552,671.858205,668.296551,679.364483,696.787227,701.244425,769.617031,750.172275,770.541884,830.455009,...,988.253380,970.587966,1052.311547,1061.350017,1048.627138,1034.755845,1051.472246,1288.542101,1532.926217,1596.245819
std,17.474539,35.780187,35.277691,23.551610,28.516854,38.427435,72.024639,51.147916,67.289664,84.751196,...,49.053185,41.417253,26.706299,26.755528,23.969496,59.288031,41.310415,60.144140,58.516004,63.116874
min,618.000000,602.777778,614.900860,650.000000,630.750000,602.550000,636.800000,626.941176,650.000000,667.500000,...,920.817500,901.227429,1001.786000,997.386560,996.546403,946.900910,966.609652,1162.705966,1403.891016,1469.825139
25%,639.200000,653.437500,651.331269,664.545455,683.928571,685.285714,740.000000,718.750000,742.222222,781.250000,...,953.135618,942.433333,1031.250000,1047.436250,1030.769720,983.506505,1016.586025,1252.448173,1514.141850,1554.942040
50%,649.166667,671.428571,664.800000,680.000000,701.250000,700.000000,770.000000,747.222222,780.771432,865.625000,...,979.658182,962.688333,1054.678570,1062.554067,1051.357999,1035.834958,1051.727557,1287.925911,1547.719670,1598.322943
75%,663.888889,682.000000,678.266667,688.200000,710.909091,717.000000,798.600000,793.333333,809.150000,887.692308,...,1014.860000,989.021015,1068.238125,1070.576345,1062.251222,1065.850671,1077.507992,1328.422446,1579.405910,1639.966446
max,691.000000,776.538462,796.666667,750.430000,761.918635,797.777778,937.500000,854.545455,950.000000,941.242232,...,1145.500000,1096.968500,1110.000000,1133.861250,1104.450000,1171.765185,1134.731786,1441.224280,1599.053750,1722.911990

In [6]:
petrol_master.mean(numeric_only=True).mean()

np.float64(1016.9822212402536)

## Diesel Checks

In [7]:
diesel_master.shape

(37, 32)

In [8]:
diesel_master.isna().sum()

State      0
2023-11    0
2023-12    0
2024-01    0
2024-02    0
2024-03    0
2024-04    0
2024-05    0
2024-06    0
2024-07    0
2024-08    0
2024-09    0
2024-10    0
2024-11    0
2024-12    0
2025-01    0
2025-02    0
2025-03    0
2025-04    0
2025-05    0
2025-06    0
2025-07    0
2025-08    0
2025-09    0
2025-10    0
2025-11    0
2025-12    0
2026-01    0
2026-02    0
2026-03    0
2026-04    0
2026-05    0
dtype: int64

In [9]:
diesel_master["State"].nunique()

37

In [10]:
diesel_master.describe()

,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,...,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02,2026-03,2026-04,2026-05
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,...,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,1055.568921,1126.690782,1153.005989,1257.061079,1341.159191,1415.058963,1403.962012,1462.975227,1379.477459,1406.051350,...,1551.881088,1277.809061,1398.574944,1409.611306,1401.629583,1361.571222,1420.171718,1648.082640,2474.690141,3277.473902
std,90.518854,91.449610,92.659056,110.278315,113.951759,142.195329,151.297830,193.625735,133.792953,161.652508,...,160.812929,95.479191,40.298900,41.129219,40.894174,90.206821,105.633064,163.551602,159.169277,190.489804
min,875.000000,897.857143,927.272727,1037.500000,1067.250000,1023.000000,1140.198333,1210.769231,1186.314163,1237.142857,...,1250.347143,1145.396667,1301.238873,1308.943231,1297.236659,1200.000000,1183.307394,1383.400000,2180.279511,2823.852839
25%,984.166667,1080.000000,1123.000000,1173.076923,1265.714286,1344.444444,1293.750000,1306.666667,1277.500000,1298.750000,...,1443.500000,1202.049700,1382.198000,1390.133429,1383.840454,1294.510975,1364.575026,1541.968672,2352.739008,3160.044755
50%,1066.000000,1136.666667,1173.619600,1250.000000,1338.000000,1405.000000,1375.000000,1433.333333,1350.000000,1364.394334,...,1554.706667,1266.325000,1400.852500,1421.695095,1408.026454,1353.369414,1409.666667,1616.252440,2472.044090,3249.955043
75%,1104.166667,1200.000000,1194.444444,1297.265297,1403.975681,1508.041637,1511.000000,1618.181818,1411.612811,1408.019995,...,1655.966387,1330.625000,1425.220000,1436.439657,1432.987940,1427.593374,1483.517835,1748.845707,2570.562522,3394.995886
max,1280.000000,1300.000000,1433.333133,1525.000000,1566.666667,1742.458333,1709.000000,1979.230769,1721.789502,1930.785714,...,1831.830000,1519.677642,1468.290000,1477.565764,1465.686225,1560.823205,1625.109836,2262.287017,2818.938152,3785.836483

In [11]:
diesel_master.mean(numeric_only=True).mean()

np.float64(1537.5150988406554)

## CPI Checks

In [12]:
cpi_food_master.shape

(34, 2)